name: Build Release Executables

# Required permissions for GITHUB_TOKEN
permissions:
  contents: write  # Required to upload files to releases
  id-token: write  # Required for authentication

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt
    
    - name: Build Windows executable
      run: python build_executable.py
    
    - name: Create ZIP archive
      run: |
        cd release-windows
        7z a -tzip ../EWI-LongTone-Visualizer-Windows.zip *
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: EWI-LongTone-Visualizer-Windows
        path: EWI-LongTone-Visualizer-Windows.zip
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: EWI-LongTone-Visualizer-Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt
    
    - name: Build macOS executable
      run: python build_executable.py
    
    - name: Create ZIP archive
      run: |
        cd release-macos
        zip -r ../EWI-LongTone-Visualizer-macOS.zip *
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: EWI-LongTone-Visualizer-macOS
        path: EWI-LongTone-Visualizer-macOS.zip
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: EWI-LongTone-Visualizer-macOS.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
